#include "mfi_test_define.h"
#ifdef EMULATOR 
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zju_simulation_handlejni_HandleJni */

#ifndef _Included_com_zju_simulation_handlejni_HandleJni
#define _Included_com_zju_simulation_handlejni_HandleJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zju_simulation_handlejni_HandleJni
 * Method:    startVisaApplication
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zju_simulation_handlejni_HandleJni_startVisaApplication
  (JNIEnv *, jobject);

/*
 * Class:     com_zju_simulation_handlejni_HandleJni
 * Method:    canBeRead
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zju_simulation_handlejni_HandleJni_canBeRead
  (JNIEnv *, jobject);

/*
 * Class:     com_zju_simulation_handlejni_HandleJni
 * Method:    initBusSimulationModules
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zju_simulation_handlejni_HandleJni_initBusSimulationModules
  (JNIEnv *, jobject);

/*
 * Class:     com_zju_simulation_handlejni_HandleJni
 * Method:    gernerSigusr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zju_simulation_handlejni_HandleJni_gernerSigusr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

#endif
